
services:
  - type: web
    name: fastapi-service
    env: python
    buildCommand: "pip install -r requirements.txt"
    #startCommand    #startCommand
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
