
services:
  - type: web
    name: fastapi-service
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
